### ISSUE TITLE
weird end deploy workflow when balancing service from node to node (not critical)

### ISSUE THREAD

**Issue by pyseed** [mlfmonde/cluster#55]
context:

node1:

node2:
service1

node2$ cd service1
node2$ docker-compose down
node2$ cd ..

cluster deploy service1 staging --master=node1

ok deployed on node1
ls -last service1 => new dir

on node2,
the old service1 is well rm
**but a new directory is pulled**
with ls -last service1 i can see i new directory that is created with service content

**Comment by petrus-v** [comment]
this is expected behavior to be able to promote the service on node2 in case of partial damage likes git host not available and so on

**Comment by petrus-v** [comment]
also this was required to properly setup buttrevolume purges, as we don't know if the script run before on slave or master, while deploying a new service k/v is not yet set so we didn't know about volumes. same while adding new volumes.

we should go deeper about different case of issues for instance we should pull and build image at the same time on both host to be ready to promote the replicate.
